name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/wrapper-validation@v4

      - name: Publish to Maven Central
        run: |
          echo $GPG_KEY_ARMOR | base64 --decode > ./release.asc
          gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc

          ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          GPG_KEY_ARMOR: "${{ secrets.SYNCED_GPG_KEY_ARMOR }}"
          GPG_KEY_ID: ${{ secrets.SYNCED_GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.SYNCED_GPG_KEY_PASSWORD }}
          SONATYPE_TOKEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
          SONATYPE_TOKEN_USERNAME: ${{ secrets.SONATYPE_TOKEN }}
          mavenCentralUsername: ${{ secrets.SONATYPE_TOKEN }}
          mavenCentralPassword: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
          signing.keyId: ${{ secrets.SYNCED_GPG_KEY_ID }}
          signing.password: ${{ secrets.SYNCED_GPG_KEY_PASSWORD }}
          signing.secretKeyRingFile: ${{ github.workspace }}/release.gpg
